package app.main.model;
// Generated Mar 15, 2017 3:38:13 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Courses generated by hbm2java
 */
@Entity
@Table(name="courses"
    ,schema="public"
)
public class Courses  implements java.io.Serializable {


     private int id;
     private String title;
     private String courseNo;

    public Courses() {
    }

	
    public Courses(int id) {
        this.id = id;
    }
    public Courses(int id, String title, String courseNo) {
       this.id = id;
       this.title = title;
       this.courseNo = courseNo;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="title")
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="course_no")
    public String getCourseNo() {
        return this.courseNo;
    }
    
    public void setCourseNo(String courseNo) {
        this.courseNo = courseNo;
    }




}


