package app.main.model;
// Generated Mar 15, 2017 3:38:13 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Exams generated by hbm2java
 */
@Entity
@Table(name="exams"
    ,schema="public"
)
public class Exams  implements java.io.Serializable {


     private int id;
     private Integer studentId;
     private Integer courseId;
     private Integer teacherId;
     private Integer mark;

    public Exams() {
    }

	
    public Exams(int id) {
        this.id = id;
    }
    public Exams(int id, Integer studentId, Integer courseId, Integer teacherId, Integer mark) {
       this.id = id;
       this.studentId = studentId;
       this.courseId = courseId;
       this.teacherId = teacherId;
       this.mark = mark;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="student_id")
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="course_id")
    public Integer getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    
    @Column(name="teacher_id")
    public Integer getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    
    @Column(name="mark")
    public Integer getMark() {
        return this.mark;
    }
    
    public void setMark(Integer mark) {
        this.mark = mark;
    }




}


