package model;
// Generated Mar 10, 2017 8:02:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Students generated by hbm2java
 */
@Entity
@Table(name="students"
    ,schema="public"
)
public class Students  implements java.io.Serializable {


     private int id;
     private String name;
     private Date birthday;
     private String groupNo;

    public Students() {
    }

	
    public Students(int id) {
        this.id = id;
    }
    public Students(int id, String name, Date birthday, String groupNo) {
       this.id = id;
       this.name = name;
       this.birthday = birthday;
       this.groupNo = groupNo;
    }
   
    @Id 
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birthday", length=13)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    
    @Column(name="group_no")
    public String getGroupNo() {
        return this.groupNo;
    }
    
    public void setGroupNo(String groupNo) {
        this.groupNo = groupNo;
    }

    @Override
    public String toString() {
        return "Students{" + "id=" + id + ", name=" + name + ", birthday=" + birthday + ", groupNo=" + groupNo + '}';
    }

}


